### ISSUE TITLE
Older Solidity version support

### ISSUE THREAD

**Issue by shogochiai** [metacontract/mc#13]
As per current commit ([257d4f5](https://github.com/metacontract/mc/commit/257d4f590b5429f3fb29013ed6b824e1fb7dfe67)), Solidity v0.8.24 is the supported version for the meta contract framework.

I'm building slot extractor [here](https://github.com/shogochiai/TextDAO/blob/master/extractorMain.ts) and it requires AST of [Schema.sol](https://github.com/shogochiai/TextDAO/blob/master/src/textDAO/storages/Schema.sol).

# Status Quo
- With some version of Foundry and Solidity, we can get `out/Schema.sol/Schema.json` with has valid ast field.
- Latest Foundry and Solidity v0.8.24 didn't give us that.
- `solc-typed-ast` is only supporting until Solidity v0.8.17

# Preferred Requirement
- `mc` to support `Solidity v0.8.17`

**Comment by kaihiroi** [comment]
It appears that [the latest release of solc-typed-ast](https://github.com/Consensys/solc-typed-ast/releases/tag/v18.1.3) now supports up to `solc 0.8.25`. Have you tried using this version to see if it provides the necessary information? If it doesn't work out, I'm considering changing the entire version of mc to accommodate this.

**Comment by shogochiai** [comment]
I'll check it and close this issue until then.
