### ISSUE TITLE
Modifier naming

### ISSUE THREAD

**Issue by shogochiai** [metacontract/mc#3]
`function propose() public predicates` ([link](https://github.com/ecdysisxyz/uds-core/blob/e2b92e880689140d1685b0aa52922a7f085967df/src/ops/consensus/ProposeOp.sol#L25)) is a bit non-intuitive.

I prefer `function main() public executable` or `function run() public runnable` for emphasising the principal function. (The "main/run" common naming can be much abstract and somewhat handy for multi-ops composability related matter.)

**Comment by kaihiroi** [comment]
I will manage these tasks as https://github.com/metacontract/mc/issues/24
